.github/dependabot.yml, .github/workflows/build_and_test.yml, .gitignore, koch.nim
* implement a bare-bones `koch` build tool
* setup a basic CI pipeline
**Koch:**
* the tool and its functionality are inspired by the tool of the same
name from NimSkull
* it only implements two very basic commands at the moment
**CI:**
* setup a basic CI pipeline that builds `koch` and runs the `all`
command
* Linux, MacOS, MacOS (M1), and Windows are used as runner systems
* configure `dependabot`
=> implement `koch` and setup basic CI pipeline

vm/vm.nim, vm/vmenv.nim, vm/vmspec.nim, vm/vmvalidation.nim
* remove the `opcIndCallCl` (call closure) instruction
* remove the `isClosure` boolean flag from `ProcHeader`
The rationale is that the built-in closure support only really covers
contemporary NimSkull closures (where the environment is passed via a
single parameter), which is too narrow a use-case (that can also be
efficiently implemented without built-in VM support) for it to warrant
a dedicated instruction.
=> vm: remove built-in closure support

.github/workflows/build_and_test.yml, koch.nim, tests/tester/example.test, tests/tester/runner.nim, tools/tester.nim
Add the `tester` tool, which is a simple test driver handling test
discovery and output checks. The actual test execution is handled on a
per-category basis via separate `runner` programs.
* add the `tester` tool and register it with `koch`
* run the tester as part of CI
* add a basic runner and test to make sure the tester works
=> setup a basic test infrastructure

koch.nim, tests/vm/README.md, tests/vm/runner.nim, tests/vm/t01_basic_program.test, tests/vm/t02_immediate_int.test, tests/vm/t03_immediate_float.test, tools/tester.nim, vm/assembler.nim, vm/vmvalidation.nim
* implement a simple assembler, with only very little abstractions over
the bytecode and VM resources
* implement a test runner for the VM and set up a test category for it
* fix procedure header validation requiring more than zero locals
* the assembler is self-contained and can be used separate from the
test runner
* it covers the full feature-set of the VM
* three basic tests are added to the VM category in order to make sure
the runner and (a subset of) the assembler work
* remove the `vm` and `vmvalidation` module from the `koch`-registered
programs. Both are now built as part of the VM's test runner
* use yellow for the color of the tester's failure reason, to
distinguish it from the runner's error output
---
* more VM tests can (and should) be added in follow-ups
=> implement an assembler for the VM

tools/tester.nim
* support multiple runner output fragments
* support custom runner arguments (provided by `arguments`)
specification
* prepare the tester for supporting an arbitrary number of runner
output fragments
* output fragments are delimited by the `!BREAK!` substring in the
runner's output
* more fragments than what the specification requires is not an error
* the `output` specification specifies what the *last* output fragment
has to be
* a file with the `.expected` extension and the same name as the test
specifies an additional output fragment
---
Both features are a preparation for implementing bytecode output comparison for the `pass0` tests in #7. The idea is that the expected bytecode is provided by a `t0x_xxx.expected` file alongside the main test file.
The various expected output …
=> expand `tester`'s features

koch.nim, vm/disasm.nim
The disassembler takes a full `VmEnv` instance and renders it into text
that the `assembler` can turn back into bytecode. It is intended mainly
for use by the test runners.
---
I've made sure locally that the disassembler works / produces the correct output. It'll be integrated into the testing pipeline as part of #7 (through integration with the `pass0` test runner).
=> implement a simple disassembler for the VM

koch.nim
It's not a tool, and making sure it compiles is done through the
`pass0` test runner (which imports the disassembler).
=> koch: remove `disasm` from program list

passes/builders.nim, passes/changesets.nim, passes/debugutils.nim, passes/lang1.md, passes/pass1.nim, passes/spec.nim, passes/trees.nim, tests/pass1/runner.nim, tests/pass1/t01_basic.expected, tests/pass1/t01_basic.test, tests/pass1/t02_multiple_locals.expected, tests/pass1/t02_multiple_locals.test, tests/pass1/t03_multiple_continuations.expected, tests/pass1/t03_multiple_continuations.test, tests/pass1/t04_split_control.expected, tests/pass1/t04_split_control.test, tools/tester.nim
The `L1` language extends the lower-level `L0` language with an
arbitrarily-sized binary data type (`Blob` type).
Since languages are currently designed bottom-to-top (i.e., lower-level
to higher-level), the higher-level language extends the lower-level
language, rather than the other way around (i.e., how it is described
in the design document).
The L1 -> L0 lowering is intended to focus on stack layout and
allocation; the `Blob` is a generalization of all aggregate data-types,
of which the exact in-memory layout is irrelevant at this stage.
The current implementation of the lowering focuses only on correctness,
with the chosen stack layout being as simple as it gets.
Fix a bug with the output stream draining in `tester`, which led to
the output returned from `exec` sometimes being cut …
=> implement a language with a blob type (`L1`)

.github/workflows/build_and_test.yml, koch.nim, passes/design.md, tools/passtool/grammar.nim, tools/passtool/parser.nim, tools/passtool/passtool.nim, tools/passtool/sem.nim
The `passtool` currently only performs some basic checks (i.e., whether
all references name existing rules and that no duplicate productions
are introduced).
In the future, it'll also provide code-generation facilities for
automating the creation of validation layers for languages. The idea is
to reduced the overhead of removing, changing, or adding new
intermediate languages as much as possible.
The tool is ran as part of CI to make sure all language grammars are
valid.
=> implement a tool for verifying language grammars

passes/changesets.nim, passes/design.md, passes/source2il.nim, passes/trees.nim, tools/passtool/sem.nim
* add the built-in `<string>` matcher for language grammars
* support `PackedTree` storing `string` values
---
* a prerequisite for more progress on the source language (e.g., strings are needed for identifiers)
=> add string support for grammars and `PackedTree`

passes/builders.nim, passes/lang_source.md, passes/source2il.nim, passes/spec.nim, passes/spec_source.nim, passes/trees.nim, tests/expr/runner.nim, tests/expr/t02_add_float_values.test, tests/expr/t02_add_integer_values.test, tests/expr/t02_sub_float_values.test, tests/expr/t02_sub_integer_values.test, tests/expr/t03_nested_calls.test
* add grammar for calls and identifiers to the source language
* add addition and subtraction for integers and floats
* implement support for `+` and `-` calls; the names are currently
hard-coded
* add very basic error handling/propagation via `tkError`
* replace the double translation of expressions with using a temporary
buffer; it's simpler, faster, and more convenient
* extend with `add` overload for appending raw node sequences
* support adding leaf nodes without there being an enclosing sub-tree
* support packed integers and floats for S-expression serialization
=> lang: add integer/float subtraction and addition

tools/passtool/sem.nim
All errors pointed to the file of the innermost language, due to
`currFile` not being restored after parsing/analyzing an `.md` file.
=> passtool: fix incorrect error positions

passes/lang0.md, passes/lang_source.md, tools/passtool/passtool.nim, tools/passtool/sem.nim
`passtool` now reports errors for unused production rules. The
motivation is preventing mistakes and to ensure that the grammars
don't accumulate garbage.
* `trim` implements the trimming, and also handles the unused
production rule reporting
* the top-level rule must be named `top`; `lang_source.md` and
`lang0.md` are adjusted accordingly
=> passtool: report unused production rules

passes/pass3.nim, passes/source2il.nim, tests/expr/runner.nim
Target the `L4` with `source2il`, so that further development of the
source language is made easier.
* adjust the generation of procedure wrapper for expressions
* apply the necessary lowerings in the `expr` test runner
* fix a bug with `pass3`, where the `Float` type wasn't considered
during type lowering
=> source2il: target `L4`

passes/source2il.nim, passes/trees.nim, tests/expr/runner.nim, tools/repl.nim
Separate `Context` creation from translation (`exprToIL`). This is a
prerequisite for incremental processing of modules.
* rename `Context` to `ModuleCtx`
* the new `open` procedure creates a new `ModuleCtx`
* the new `close` procedures finishes the `ModuleCtx` and yields the
produced IL code
* `exprToIL` appends a proc to `Context` and only returns the type  
* `Literals` can now be appended to directly, without a `PackedTree` 
* `Context` now accumulates its own `Literals` DB, instead of re-using
that of the input tree(s)
---
* part of the work of introducing modules and procedure declarations
=> source2il: separate `Context` creation

passes/pass0.nim, tests/pass0/t03_unreachable.expected, tests/pass0/t03_unreachable.test, vm/assembler.nim, vm/vm.nim, vm/vmspec.nim, vm/vmvalidation.nim
When executing an `Unreachable` instruction, the VM unconditionally
exits with an error of the L0 language.
The opcode is added for the convenience of the code generator / higher-
level passes: a procedure ending in an `Unreachable` statement now no
longer requires an (unnecessary) exit continuation in order to result
in well-formed bytecode.
While `pass0` could relatively easily insert a `Ret` instruction to
make the bytecode well-formed, the dedicated instruction has the
benefit that it aborts execution.
---
* part of implementing `Unreachable` for the source language
=> vm: add `Unreachable` opcode

passes/source2il.nim, passes/spec_source.nim, spec/spec.md, tests/expr/t02_unreachable.test, tests/expr/t05_return_operand_cannot_be_void.test, tests/expr/t05_unreachable_is_void.test, tests/expr/t06_call_proc_with_void_return_type.test
* add the `Unreachable` expression
* add the `VoidTy` type expressions
* support procedures with a `void` return type
`Unreachable` is intended to mark control-flow paths as dead. Future
progress on the language might render it obsolete again, but for now,
it fills a hole in the language and, in the absence of a `raise`-like
construct, makes `void`-return procedures (and thus `void` call
expressions) possible.
---
* depends on #34
=> lang: add `Unreachable` and `void` procedures

passes/pass4.nim, tests/pass4/t04_continue_with_local_return.expected, tests/pass4/t04_continue_with_local_return.test
Fix a bug with `pass4` where references to locals within a `Continue`'s
expression were not patched, leading to code generation failures or
incorrect behaviour at run-time.
Instead of the expression's index, the node index of the continuation
ID was passed to `lowerExpr`. A test is added to make sure the lowering
works properly now.
---
* discovered as part of #36
=> pass4: fix locals not being processed

common/vmexec.nim, passes/source2il.nim, passes/spec_source.nim, phy/types.nim, spec/spec.md, tests/expr/runner.nim, tests/expr/t02_tuple_constructor_1.test, tests/expr/t02_tuple_constructor_2.test, tests/expr/t02_tuple_constructor_3.test, tests/expr/t02_unit_constructor.test, tests/expr/t03_unit_in_tuple.test, tests/expr/t03_void_in_tuple.test, tests/expr/t04_proc_declaration.test, tests/expr/t06_call_proc_with_tuple_return_type.test, tests/expr/t06_call_proc_with_unit_return_type.test, tools/repl.nim, vm/vm.nim
* implement tuple type constructors
* implement tuple constructors
* implement general support for aggregate/complex types for `source2il`
and the tester
* since types can be more complex now, they're represented by the new
`SemType` type
* move the type representation and corresponding query routines to the
new `types` module
* implement tuple and tuple type constructor support
* implement support for returning aggregate/complex types from
procedures. They currently need to be returned via an out parameter
* implement expression-list lowering. They're needed for the out
parameter handling, but the `L10` doesn't support them yet
* support setting the start of the stack with `initThread`
* implement support for aggregate return values for `vmexec.run`
=> lang: add tuple types and tuples

passes/source2il.nim, phy/default_reporting.nim, phy/reporting.nim, tests/expr/runner.nim, tools/repl.nim
* implement a generic reporting system (`ReportContext`), intended for
use by the compiler
* integrate `ReportContext` into `source2il`
* the REPL and the `expr` test runner now report a text message for
each error
* add the `reporting` and `default_reporting`, containing the
`ReportContext` type and a simple implementation thereof,
respectively
* require an `ReportContext` instance when creating a `ModuleCtx`
* in `source2il`, report an error message whenever detecting an error
* adjust the tester runner and the REPL to the new error reporting.
Whether an error occurred is now indicated by there being an
unprocessed message in the report context
The error messages are currently formatted in-place, but the idea is to
eventually send dedicated message objects (which store all necessary …
=> implement a reporting system

tests/vm/t04_float_local.test, tests/vm/t04_float_local_set.test, tests/vm/t04_int_local copy.test, tests/vm/t04_int_local.test, tests/vm/t04_stack_alloc.test, tests/vm/t05_read_write_float32.test, tests/vm/t05_read_write_float64.test, vm/vm.nim, vm/vmvalidation.nim
* fix `WrFlt32` and `LdFlt32` not working correctly
* fix a validator bug with `WrFlt32` and `WrFlt64`, where valid code
was treated as invalid
The implementation of `LdFlt32` and `WrFlt64` didn't consider that
there are only 64-bit float registers, *casting* (not converting)
between 64-bit values and 32-bit floats and thus producing bogus
results.
The 64-bit float value is now *converted* to or from a 32-bit float
when doing a 32-bit load or store, respectively, fixing the issue.
Finally, tests for float load and store instructions are added.
Since the assembler/VM features they depend on weren't tested yet,
tests are added for those too.
---
* discovered as part of #39
=> vm: fix load and store for floats

passes/source2il.nim, passes/spec_source.nim, spec/spec.md, tests/expr/t03_tuple_access_1.test, tests/expr/t03_tuple_access_2.test, tests/expr/t03_tuple_access_3.test, tests/expr/t03_tuple_access_out_of_bounds_1.test, tests/expr/t03_tuple_access_out_of_bounds_2.test
Extend the source language with the `FieldAccess` operator, for
retrieving values from a tuple. Only static indexing with immediate
integer values is supported at the moment.
=> lang: add tuple access

passes/lang3.md, passes/pass3.nim, tests/pass3/t04_asgn_aggregate.expected, tests/pass3/t04_asgn_aggregate.test, tests/pass3/t04_asgn_sub_aggregate.expected, tests/pass3/t04_asgn_sub_aggregate.test, tests/pass3/t04_load_aggregate.expected, tests/pass3/t04_load_aggregate.test, tests/pass3/t04_store_aggregate.expected, tests/pass3/t04_store_aggregate.test
Add support for assigning, storing, and loading aggregate values to
`L3`, and thus to all higher-level languages extending it. This is a
prerequisite for removing the assignment lowering from `source2il`. 
Assignments and stores of aggregate values are lowered into memory
copies (`Copy`) by `pass3`. `pass3` is currently the best pass to
implement this lowering in, since it also does the lowering of other
aggregate-related operations.
---
* removing the assignment lowering from `source2il` will remove some conditional
logic and complexity from the latter
=> lang3: support aggregate assignments

passes/pass10.nim, tests/pass10/t03_ssa_loop_3.expected, tests/pass10/t03_ssa_loop_3.test
Fix a bug with propagation of needed locals in `pass10` that resulted
in crashes for locals needed across a loop edge.
The test for detecting the loop start during backward propagation
was wrong. It triggered immediately for the basic-block ending in
the loop edge, thus disabling reiteration for the rest of the loop's
basic-blocks, which resulted in incorrect `needs` sets.
The condition is corrected and a test case for reproducing the issue is
added.
=> pass10: fix propagation of needed locals

passes/source2il.nim
Remove the special case of the trailing statement in a void expression
having to be placed in the `Expr.expr` part, simplifying the `exprToIL`
post-conditions.
* require the `expr` part of `Expr` to be empty for `void`
expressions and non-empty for non-`void` expressions (except
`tkError` ones)
* add assertions to verify that the post-conditions are satisfied
* adjust the IL generation logic accordingly
* move the `Return` void check to before expression fitting
In addition, `genAsgn` now ignores void expressions, so that one can
write
```nim
c.genAsgn(..., e.expr, e.typ, bu)
```
instead of
```nim
if e.typ.kind != tkVoid:
c.genAsgn(..., e.expr, e.typ, bu)
```
=> source2il: simpler `Expr` rules

passes/source2il.nim, spec/spec.md, tests/expr/t06_redeclaration_error_3.test
* an error is now reported when using the name of a built-in for a
procedure or type declaration
* error messages for using entities in an incorrect context are
improved
* `false` and `true` are now treated as built-ins
* the internal implementation of lookup is improved
The specification already said that built-in names were disallowed, but
`source2il` didn't adhere to it.
* add the `lookup` procedure, implementing lookup in a single place
* replace all manual `scope` lookup with `lookup`
* add a table that keeps track of all built-in entities
* improve error messages for unexpected entity kinds
* list `true` and `false` as names automatically part of every scope
Instead of adding the built-ins to `scope`, the constant `BuiltIns`
table is queried as a fallback when lookup in `scope` …
=> source2il: disallow using built-in name for declaration

passes/pass10.nim, tests/pass10/t03_ssa_loop_4.expected, tests/pass10/t03_ssa_loop_4.test, tests/pass10/t03_ssa_loop_5.expected, tests/pass10/t03_ssa_loop_5.test, tests/pass10/t03_ssa_loop_6.expected, tests/pass10/t03_ssa_loop_6.test, tests/pass10/t03_ssa_loop_7.expected, tests/pass10/t03_ssa_loop_7.test
Fix both the reaching definitions and liveness analysis not handling
nested loops correctly, resulting in compiler crashes or
miscompilation.
Only iterating the outermost loop twice doesn't ensure that a fixpoint
is reached -- it necessary to process *every* loop 2 + N times, where N
is the nesting depth. The documentation of both analysis passes is
improved to better describe what they do and why they work like they
do.
Tests are added to ensure that nested loops are handled correctly.
Except for `t03_ssa_loop_4`, the previous implementation produced
incorrect code for the new tests.
=> pass10: fix nested loop data-flow analysis

tests/vm/t04_bitnot.test, vm/assembler.nim, vm/vmvalidation.nim
* fix validation for `opcBitNot` expecting two inputs (instead of only
one)
* support integers in hexadecimal form (both `0xn` and `#n`) with the
assembler
The `opcBitNot` operation only needs a single stack operand, but the
validation required two. This is now fixed, and a test for `opcBitNot`
is added to make sure validation and execution of it works.
For convenience of writing the test, the assembler is extended to
support integers in hexadecimal form in all places where integer
numbers are expected.
---
* discovered while testing the VM with bytecode generated from a real-world codebase
=> vm: fix `opcBitNot` validation

passes/pass0.nim, tests/pass0/t03_bitand.expected, tests/pass0/t03_bitand.test, tests/pass0/t03_bitor.expected, tests/pass0/t03_bitor.test
The implementation erroneously treated the trees as having only two
child nodes, while they actually have three (type, operand a, operand
b).
---
* discovered while testing the pass with some real-world code
=> pass0: fix `BitAnd` and `BitOr` translation

common/vmexec.nim, koch.nim, passes/spec.nim, passes/spec_source.nim, passes/trees.nim, phy/nim.cfg, phy/phy.nim, tests/pass0/runner.nim
Bundle the passes, `source2il`, the assembler, and the VM into a single
CLI application. The idea with it is to help with development, by
providing a convenient way to invoke the passes/VM/etc. and inspect the
(intermediate) output.
The `phy` program provides a small command line interface for
specifying the source and target language are, what IRs to print, and
what to do (only compile or also evaluate).
Much of the implementation is copied from the various test runner:
* `source2il` invocation and comes from the `expr` test runner
* rendering VM execution results without high-level type information
is moved over from the `pass0` test runner (into `vmexec.nim`)
The program also provides the `--runner` option, which makes it
behave in a way such that it's suitable as being used as a test …
=> add the `phy` CLI application

.github/workflows/build_and_test.yml
Update the non-arm MacOS runner to the `macos-13` image. The currently
used `macos-12` image is [deprecated](https://github.com/actions/runner-images/issues/10721) and will soon become unsupported.
=> ci: update MacOS runner

passes/source2il.nim, passes/spec_source.nim, spec/spec.md, tests/expr/t12_and_result_1.test, tests/expr/t12_and_result_2.test, tests/expr/t12_and_result_3.test, tests/expr/t12_and_result_4.test, tests/expr/t12_and_scoping.test, tests/expr/t12_and_scoping_error.test, tests/expr/t12_and_short_circuit.test, tests/expr/t12_and_typing_1_error.test, tests/expr/t12_and_typing_2_error.test, tests/expr/t12_or_result_1.test, tests/expr/t12_or_result_2.test, tests/expr/t12_or_result_3.test, tests/expr/t12_or_result_4.test, tests/expr/t12_or_scoping.test, tests/expr/t12_or_scoping_error.test, tests/expr/t12_or_short_circuit.test, tests/expr/t12_or_typing_1_error.test, tests/expr/t12_or_typing_2_error.test
Add the logical `And` and `Or` operators to the source language.
Both operators short-circuit evaluation of the second operand. For this
reason, dedicated expression kinds are used instead of built-in calls.
Since the second expression of both `And` and `Or` is evaluated
conditionally, it is analyzed within its own scope in order to prevent
declarations therein from being visible to the outside -- such locals
would be in an undefined state when the expression is not evaluated.
`And` is implemented as the statement version of `(If a b False)`; `Or`
is implemented as the statement version of `(If a True b)`.
=> lang: add the logical `And` and `Or` operators

passes/source2il.nim, tests/expr/t13_usage_in_and.test, tests/expr/t13_usage_in_if_cond.test, tests/expr/t13_usage_in_not.test, tests/expr/t13_usage_in_or.test, tests/expr/t13_usage_in_return.test
Fix a `source2il` translation bug causing internal syntax errors when
using locals as `not`, `And`, `Or`, `If` or `Return` operands.
In the L30 language, loading the underlying value stored in a local
requires using `Copy` (which is also enforced by the gramamr). This was
not considered everywhere in `source2il`, leading to the L30 output
having syntax errors.
The problematic translation is changed to use `genUse` instead of
`inline` or manually adding the node sequences. For convenience, a
`genUse` overload is added that takes an `Expr`.
A test is added for each case where compilation previously failed.
---
* discovered as part of #67 
* I've audited every use of `inline` and every manual appending of `Expr.expr` for whether it's correct
=> source2il: fix code generation for usage of locals

passes/pass0.nim, tests/pass0/t03_conv_float64_to_32.expected, tests/pass0/t03_conv_float64_to_32.test
Fix code generation for float demotion. The previously generated code
did not pass bytecode validation.
With float value `x` on the operand stack, the instruction sequence
`StackAlloc` + `Swap` + `Dup` results in the operand stack
`x, x, address` (from top to bottom), which is incorrect and fails
validation, as `opcWrFloat32` expects one int and one float input, not
two float inputs.
Memory operations are not needed for implementing float demotion at
all. Reinterpreting the float value as a 32-bit integer (which
internally demotes the float value) first and then reinterpreting the
integer as a 32-bit float suffices.
---
* the bug was discovered with the help of [skully](https://github.com/nim-works/phy/pull/70)
=> pass0: fix `Conv` for float-to-float conversions

passes/source2il.nim, passes/spec_source.nim, spec/spec.md, tests/expr/t15_while_1.test, tests/expr/t15_while_2.test, tests/expr/t15_while_body_must_be_unit_error.test, tests/expr/t15_while_body_must_be_unit_or_void_error.test, tests/expr/t15_while_cond_must_be_bool_error.test, tests/expr/t15_while_scoping_1.test, tests/expr/t15_while_scoping_2_error.test, tests/expr/t15_while_scoping_3_error.test, tests/expr/t15_while_true.test, tests/expr/t15_while_true_complex_error.test, tests/expr/t15_while_unit_body.test, tests/expr/t15_while_void_body.test
Add the `While` loop construct to the source language. A `While` loop
repeatedly evaluates a given unit expression as long as the given
condition evaluates to true.
A `While` loop is implemented as a `Loop` + conditional `Break` in the
target IL.
At the moment, a `(While (Ident "true") ...)` is always typed as
`void`, as - without a `Break`-like statement - control-flow can never
reach the code immediately following the loop. Due to the current lack
of early constant folding, detection of such loops needs to be syntax-
based, and thus more complex cases (such as `(Exprs (Ident "true"))`)
are *not* typed as `void`.
=> lang: add `While` loops

passes/spec.nim, passes/spec_source.nim, passes/trees.nim
In S-expressions representing source language code, symbols and numbers
can now appear anywhere. If not appearing in a special position,
they're parsed as `(Ident x)` and `(IntVal x)`/`(FloatVal x)`,
respectively.
For example, `(Asgn (Ident "x") (IntVal 1))` can now be written as
`(Asgn x 1)`.
Standalone symbols and numbers can be unambiguously parsed as `Ident`
and `IntVal`/`FloatVal` nodes. The aim is to make writing source
language code easier (until a non-S-expression syntax is developed).
In terms of implementation, `tree.fromSexp` now calls the generic
`fromSexp` and `fromSexpSym` procedures provided for the node kind
enum.
For `spec_source` (the source language tree representation), standalone
symbols parse as `Ident`, floating-point numbers as `FloatVal`, and
integer numbers as …
=> support standalone numbers and symbols in source code

passes/spec.nim, passes/spec_source.nim, passes/trees.nim, phy/phy.nim, phy/tree_parser.nim, tools/repl.nim
Add a parser for `PackedTree`s that operates directly on S-expression
strings, without going through an intermediate `SexpNode` tree.
* move the existing `fromSexp` procedure from `trees` to `tree_parser`
* add the `parseSexp` and `fromSexp` procedures to `tree_parser`, both
which take a `string` as the parameter. The parser reuses the
existing lexer/parser provided by `SexpParser`
* change the generic `fromSexp` interface procedure to take a typed
value and `Literals` object as input, instead of a `SexpNode` and
`PackedTree`, making them more generally applicable
* update the `fromSexp` usages in `phy.nim`; first parsing an S-
expression into a `SexpNode`. This should speed up a parsing a little
---
* the parser deliberately doesn't recurse into itself, so that arbitrarily nested trees …
=> implement a `string` -> `PackedTree` parser

passes/lang0.md, passes/pass0.nim, passes/pass25.nim, passes/pass3.nim, passes/spec.nim, tests/pass25/t03_ssa_addr_keep_alive_5.expected, tests/pass25/t03_ssa_addr_keep_alive_5.test, tests/pass3/t04_asgn_aggregate.expected, tests/pass3/t04_asgn_sub_aggregate.expected, tests/pass3/t04_load_aggregate.expected, tests/pass3/t04_store_aggregate.expected
Instead of `Copy`, the memcopy/blit operation is now named `Blit`,
making it clearer what the operation does.
Both the copy and memcopy operation used the name `Copy`, which -
besides being confusing - made searching for either of them using just
the node kind impossible (the shape had to be considered for
discriminating between them).
---
* this is a split-out from the pass rework
=> lang0: rename blit operation to `Blit`

passes/lang0.md, passes/pass0.nim, tests/pass0/t03_basic_global.test
Require definitions of global variables to also provide a type, instead
of just a literal value (from which the type is inferred).
Having an explicit type is a requirement for querying the type of
expressions with a global variable at the root, something which is not
implemented at the moment, but will be needed by future passes
(especially once the source language supports globals).
Having a dedicated node kind / subtree for a global definitions also
makes it easier/possible to extend the definition with additional
information (such as whether the global is mutable).
---
* a split-out from the pass rework
=> lang0: make globals explicitly typed

passes/ir.nim, passes/source2il.nim
Construct IL expressions and statements using a nested tree-based IR,
replacing the usage of `Builder` and making tree construction easier to
read and write.
`source2il` has to perform various lowering intermixed with analysis at
the moment, which makes the `Builder` API cumbersome and noisy to use
for constructing the trees.
Using a tree-based IR - where each node stores all its transitive child
nodes - makes construction much easier, at the cost of more allocator
activity (since each node with subnodes allocates its own `seq`). The
IR also handles some additional details, like packing numeric values
and wrapping lvalue expression, further simplifying construction.
The tree-based IR only covers the statements and expressions, not
things like procedures and types. Various procedures are …
=> source2il: use a tree-based IR

passes/source2il.nim
Treat return values and parameters of aggregate type like any other
in `source2il`, leaving lowering them into pointer parameters to the
lowering passes.
---
* a follow-up to #85, which introduced the aggregate parameter lowering
=> source2il: remove aggregate parameter lowering

passes/source2il.nim, tests/expr/t06_call_result_field_access.test
Fix `source2il` crashing for call expressions used as the `FieldAccess`
operand.
Add the `inlineLvalue` procedure, which commits `L30` r-value
expressions to a temporary and then return the temporary. Since the
`FieldAccess` translation wants an `L30` l-value, it now uses the
new `inlineLvalue`.
With the removal of the aggregate return value lowering from
`source2il`, call expressions that return a tuple no longer use a
temporary. This resulted in `(Field (Call ...) ...)` `L30` trees,
which are not allowed by the `L30` grammar.
---
* a regression introduced by #90
=> source2il: fix calls used as `FieldAccess` operand

tests/vm/runner.nim, tests/vm/t03_import.test, vm/assembler.nim
Add the `.import` directive to the assembler, which makes it possible
to express imported/foreign procedures in assembler code.
The import name uses double-quotes, even though the currently
supported character set doesn't require quotation. This is only
for reasons of style and readability, to highlight that the name
isn't a normal identifier.
---
A blocker for #70. The upcoming test for skully needs to disassemble and reassemble a VM module, and imported/foreign procedures don't roundtrip at the moment.
=> assembler: add the `.import` directive

passes/pass0.nim, tests/vm/runner.nim, tests/vm/t06_export_global.test, tests/vm/t06_export_procedure.test, tests/vm/t07_export_import_procedure.test, vm/assembler.nim, vm/vmmodules.nim, vm/vmvalidation.nim
* add support for exported procedures and globals to VM modules
* implement procedure import resolution for `vmmodules.link`
Procedures and global variables can now be marked as exported, by
adding them to the `export` table; the assembler provides this
functionality through the new `.export` directive. The same global
variable or procedure can be exported multiple times.
Exported procedures are used to resolve procedure imports, which
the `pkCallback` entries are repurposed to represent prior to
linking. The host procedure table is now only tried when a
procedure import doesn't resolve to an exported procedure; if
that fails too, the procedure is turned into a stub.
Global variables cannot be imported at the moment, but being able
to export them is still useful for looking them up from …
=> vmmodules: support exported procs/globals

phy/phy.nim, tests/pass0/t05_foreign_procedure.expected, vm/disasm.nim
Change `disassemble` to take a VM module as input instead of a VM
instance (`VmEnv`), restoring the symmetry between the disassembler and
assembler (the latter which produces a `VmModule`).
* change the parameters in `disasm` from `VmEnv` to `VmModule`
* add rendering for module exports to `disassemble` 
* update the `pass0/t05_foreign_procedure.test` expected output, which
now shows the imported procedure
---
* this completes the move to making `VmEnv` the internal-only execution environment representation
=> disasm: disassemble `VmModule` instead of `VmEnv`

tests/vm/t03_neg_int_overflow.test, tests/vm/t05_div_int_div_by_zero.test, tests/vm/t05_div_int_overflow.test, tests/vm/t05_divu_div_by_zero.test, tests/vm/t05_float_to_sint_1.test, tests/vm/t05_float_to_sint_2.test, tests/vm/t05_float_to_sint_3.test, tests/vm/t05_float_to_sint_4.test, tests/vm/t05_float_to_uint_1.test, tests/vm/t05_float_to_uint_2.test, tests/vm/t05_float_to_uint_3.test, tests/vm/t05_float_to_uint_4.test, tests/vm/t05_mod_int_div_by_zero.test, tests/vm/t05_modu_div_by_zero.test, vm/assembler.nim, vm/vm.nim, vm/vmvalidation.nim
Make the behaviour of all operations well-defined for all inputs and
fix the implementation of some operations exhibiting undefined
behaviour for some inputs.
The implementation of some opcodes used unchecked signed integer
arithmetic or conversions, thus triggering defects when building with
checks and undefined behaviour otherwise.
There's no sensible to value that can be returned for a integer
division by zero, so the `MulU`, `DivU`, `DivInt`, and `ModInt`
operations all trap (raise a run-time error) now.
The `FloatToSInt` and `FloatToUInt` operations now perform a saturating
conversion, clamping the float value to the specified integer range.
NaNs are always converted to 0. The validator now also makes sure that
their immediate operand is a legal value.
For `low(int64)`, `NegInt` and …
=> vm: remove undefined behaviour

.github/workflows/build_and_test.yml
Pin the NimSkull version used to the most recent working one
(0.1.0-dev.21431), making it the official minimum supported version of
NimSkull to compile the various Phy programs with.
---
* this fixes the CI failures caused by the most-recent broken NimSkull release
* [skully](https://github.com/nim-works/phy/pull/70) also needs a pinned version, as it imports compiler modules directly
=> ci: pin the NimSkull version

passes/lang0.md, passes/pass0.nim, passes/spec.nim, tests/pass0/t03_basic_global.expected, tests/pass0/t05_export_global.expected, tests/pass0/t05_export_global.test, tests/pass0/t05_export_procedure.expected, tests/pass0/t05_export_procedure.test, tests/pass0/t05_foreign_procedure.test, vm/disasm.nim
Add export lists - for exporting procedures and globals - to the `L0`
and all ILs extending it. The concept of *foreign procedures* is
changed into the more general *imported procedure* one.
A `Module` sub-tree may now have an optional trailing `List` sub-tree
containing a list of `Export` trees, which are translated directly into
VM module exports.
The `Foreign` node kind is renamed to `Import`. No further change is
required, as `L0` `Foreign` procedures are translated to `pkCallback`
procedure headers, which already represent procedure imports.
In addition, the disassembler output for global variables not being
valid assembler code is fixed.
---
* further progress towards multi-module support
* support for exported globals in the ILs is a prerequisite for the allocator
=> lang0: support exporting procedures/globals

passes/source2il.nim, spec/spec.md, tests/expr/t09_decl_decl_with_same_name_in_initializer.test, tests/expr/t12_and_scoping_1.test, tests/expr/t12_and_scoping_2_error.test, tests/expr/t12_and_scoping_3_error.test, tests/expr/t12_or_scoping_1.test, tests/expr/t12_or_scoping_2_error.test, tests/expr/t12_or_scoping_3_error.test, tests/expr/t15_while_scoping_1_error.test
By default, expressions now always open a new scope for themselves and
their sub-expression, except for the first operand of `And`/`Or`,
expressions in `Exprs`, and `If` conditions.
The new scoping rules are much easier to formalize, as a `(Decl a b)`
expressions can now be viewed as `(Let a b trailing)`, where `trailing`
are the following expressions in the enclosing `Exprs`.
The rules arguably also make reasoning about code slightly easier to
the reader, as declarations within some nested sub-expression don't
"escape" outwards anymore.
For the implementation, `scopedExprToIL` is renamed to `exprToIL` and
the former `exprToIL` is renamed to `openExprToIL`.
The change is a preparation for formalizing the language definition.
In the future, some of the previous scoping rules might be …
=> lang: use more structured scoping rules

common/vmexec.nim, passes/source2il.nim, phy/phy.nim, tools/repl.nim
Implement an allocator for internal use by the `source2il`, for
implementing language features that require heap locations (e.g.,
dynamic arrays).
The allocator is a simple bump-pointer allocator backed by a static
memory region. It consists of three procedures: `alloc`, `dealloc`, and
`realloc`. Since the source language doesn't support the features
necessary for implementing the allocator, the aforementioned procedures
are implemented in `L30` code provided via inline strings.
`dealloc` is currently a no-op, meaning that memory is never freed.
Upon exhausting the available heap memory, an exception is raised,
which currently results in undefined behaviour (as `CheckedCall` isn't
used for call expressions).
To reduce implementation complexity, the allocator procedures are
always added to …
=> source2il: implement a simple allocator

passes/pass0.nim, tests/pass0/t03_bitnot.expected, tests/pass0/t03_bitnot.test, tests/pass0/t03_bitxor.expected, tests/pass0/t03_bitxor.test
Fix the translation of `BitNot` to bytecode resulting in incorrect
results for non-64-bit signed integers.
The result of the `opcBitNot` instruction was always masked, even for
signed integers, which is incorrect, as it invalidates the two's
complement representation. For example, `not 2'u32` should be -3,
but with the subsequent 32-bit masking it was 4,294,967,293‬
(`0xFF_FF_FF_FD`).
A mask instruction is now only emitted for unsigned integers. In
addition, an unnecessary but otherwise harmless `opcMask` instruction
was emitted for both `BitXor` (uint) and `Shl` (int), which is also
fixed.
---
* discovered with #70 (and also a blocker thereof)
=> pass0: fix `BitNot` for signed integers

tests/vm/t03_import_bug.test, vm/vmmodules.nim
Fix a bug with computing the link table, which resulted in faulty VM
environments for non-trivial VM modules using imports.
The `i` variable in the inner `for` loop of the link-table computation
was incorrectly shadowed, leading to the wrong table entry being set.
This, in turn, could lead to the entry of a non-imported procedure being
turned into a callback entry.
---
* discovered with #70 (and also a blocker thereof)
=> fix bug in linker's import resolution

.github/workflows/build_and_test.yml, koch.nim, spec/spec_old.md, spec/specification.md
Replace the informal definition of the source language's syntax and
semantics with a formal one. This provides the basis for deriving
proofs of correctness in the future, as well as for proving that the
language is *type safe* (among other properties).
The formal definition attempts to capture the full current semantics of
the source language. To make the static and dynamic semantics simpler
to express, a *language core* is defined, which the source language
*desugars* to.
Same as before, the operational semantics of floating-point arithmetic
is not defined at the moment. In future work, it should be defined
according to the IEEE 754.2008 standard.
Where the formal definition (deliberately) differs from both the
informal one and currently implemented behaviour is integer overflow:
the new …
=> spec: add a formal definition of the source language

common/vmexec.nim, passes/source2il.nim, passes/spec_source.nim, phy/type_rendering.nim, phy/types.nim, spec/specification.md, tests/expr/t18_seq_character_string_1.test, tests/expr/t18_seq_character_string_2.test
Add string constructors (`(Seq "...")`) and the `CharTy` type to the
source language. Both are meant as an interim solution to making
working with text easier.
* add the static and dynamic semantics for string constructors. A
"character" is considered a UTF-8 byte, with the `(Seq "...")`
constructing a dynamic array with the UTF-8 bytes of the given
unicode string
* S-expression strings are automatically translated to
`(StringVal ...)` during parsing
* add the `tkChar` type kind and implement the associated logic (type/
value rendering, IL translation)
A `(StringVal ...)` is a static array (i.e., an array of statically
known size), and thus it's not considered to be a string constructor
itself.
---
* meant as a preparation for adding some basic I/O procedures
* my current plan is for …
=> lang: add string constructors

passes/source2il.nim, phy/host_impl.nim, spec/specification.md, tests/expr/t19_write.test, tests/expr/t19_writeErr.test
Add support for writing to the standard output and error output to the
source language, via the built-in `write` and `writeErr` procedures.
For convenience, both output procedures take a `(SeqTy (CharTy))` value
as input. Internally, the built-ins invoke their corresponding external
procedure, which takes a data pointer and length as input.
Same as the allocator procedures, both new built-in procedures are
always added to a module, even if not used.
The operational semantics of both output procedures is modeled as
appending to an array stored in the context.
---
* in the future, both `write` and `writeErr` should become non-built-in procedures (somehow)
=> lang: add `write` and `writeErr`

phy/host_impl.nim, phy/phy.nim, phy/repl.nim, phy/vmexec.nim
Allow for configuring at run-time where to write the output and error
text for the VM host procedures. This is an internal change aimed at
making debugging and testing easier.
* require providing the output and error streams to use for
`core.write` and `core.writeErr` via the `HostEnv` instance
* support passing an environment closure (`RootRef`) to the VM via the
type-information `vmexec.run` overload
* rename `writeToFile` to `writeToStream` and have it take a `Stream`
as the destination rather than a file
This also fixes `core.writeErr` always writing to the standard output
stream (`writeToFile` always used `stdout`, ignoring the file
argument).
---
* a small improvement unrelated to any other ongoing work
=> host_impl: make output streams configurable

passes/source2il.nim, phy/types.nim
Implement internal support for locations with an alignment requirement
greater than 1 byte. This is a preparation for the source language
gaining type alignment requirements.
The alignment for numeric types (int and float) is equal to their size,
while for aggregate types (other than `seq`) it's that of their most
aligned constituent type.
The size of aggregate types is padded to be a multiple of their
alignment. This is so that their size matches the space they would take
up within an array, while still allowing copying `size` bytes from a
pointer to a location of said type to be valid, regardless of where the
location is located. Record fields are placed such that their relative
offset is a multiple of their alignment requirement.
The allocator procedures `alloc` and `realloc` take an …
=> source2il: implement alignment support

languages/source.nim, spec/langdefs.nim
Instead of a list of assignments of the form `<f> <pattern>* = <body>`,
the body of a meta-function must now be a `case` expression.
A function such as:
```
function f, x -> x:
f(z) = 1
f(1) = 2
```
is now written as:
```
function f, x -> x:
case _
of z: 1
of 1: 2 
```
The two reasons for this change are:
1. there's no point in repeatedly specifying the name of a function:
it's the only valid identifier that may appear in before the
parenthesis. It's presence only introduces visual noise and makes
it harder to rename functions
2. the assignment based syntax is a bit trickier to parse, and it's
arguably not very intuitive. For people already familiar with
NimSkull and its syntax, what the new `case` expression syntax does
is likely easier to understand
Using a `case` expression also makes …
=> langdefs: use `case` expression for function bodies

languages/source.nim
Express the semantics of `readFile` using the currently available
meta-language features.
The previous idea boiled down to treating the result of `readFile` as
fully random (within the bounds of the value's inhabited type). This is
wrong, as it *is* possible to precisely know the value, where afforded
by the context.
The dynamic execution context is extended with a function that maps a
file path and "time" to a UTF-8 character sequence, which is used to
provide the result of a file system read access. The purpose of the
time value is to model the fact that successive reads with the same
path may yield different results, without the program changing anything
itself. Without the time parameter, the definition - due to the meta-
language's side-effect free nature - would define `readFile` as …
=> spec: clarify `readFile` semantics

languages/source.nim
Replace the type shorthands (`"int"`, `"float"`, etc.) with the
real syntax (`IntTy()`, `FloatTy(),` etc.) in the formal definition.
The type shorthands were originally intended to make the definition
easier to read, but they're currently defined as if they were separate
syntactic constructs (which they're not).
They're replaced with the type syntax they stand for, bringing the
language definition closer to what was/is intended.
---
* a small preparation for #114
=> spec: replace the type shorthands

koch.nim, phy/queryshell.nim, phy/repl.nim, phy/sexpstreams.nim, spec/interpreter.nim
Add a simple command-line shell to query `LangDef`s with and execute
their functions and relations. The source language is currently
hardcoded as the language to query.
The shell is intended to aid with language development, by providing a
convenient way to test relations and functions with various input.
For ease of implementation, commands are provided as S-expressions.
Result values are also rendered as S-expressions. Constructors for
built-in meta-language terms (e.g., `true`, `false`, tuples, etc.) are
prefixed with a colon to distinguish them from user-defined type
constructors.
In addition, to showing the result of a function/relation application,
the shell also shows the interpreter-generated trace of which
relations.
* move the line-buffered stream and S-expression parsing …
=> add a command-line shell for `LangDef` queries

spec/interpreter.nim
Fix plug-patterns nested in other plug-patterns (e.g., `E[E[...]]`)
being ignored during interpretation.
Plug patterns need special two-step handling, the simple pattern
matching (`matches`, which is the first step) used by the continuation
passed to the `matchesRPattern` call is not enough (it unconditionally
reports a match for plug patterns), leading to nested plug-patterns
effectively being ignored.
The pattern matching from the `nkMatches` handling (which takes care of
the second step) is factored into the dedicated `interpretMatch`
procedure, which calls itself in order to handle the plugged-with
pattern.
---
* unblocks #127
=> interpreter: fix nested plug-pattern matching

languages/source.nim, spec/langdefs.nim
* use native `func` syntax for function definitions, which allows for
named parameters
* allow all valid meta-language identifiers to be used as `let` names
* support tuple unpacking in `let` statements
* adjust the source language definition to the new syntax
The changes are aimed at making it possible to express the same functions
in less code.
* replace the `function`-statement syntax with the native `func` syntax
* remove the `case _` construct, which is no longer needed now that
there's named parameters
* implement scoping properly. Only the identifiers introduced within an
`if`, `else`, and `of` branch are discarded at their end
* move all non-pattern binding introduction logic into the `addBinding`
procedure
* disallow `_` as a forvar name (an identifier is currently required …
=> langdefs: improve function syntax

languages/source.nim, passes/source2il.nim, tests/expr/spectest.nim, tests/expr/t05_proc_with_non_void_body.test, tests/expr/t05_proc_with_non_void_body_error.test, tests/expr/t05_proc_with_non_void_body_subtype.test
Allow any non-void expression as procedure's body, as long as its type
fits the return type. This reduces `Return` noise and allows for more
functional-style procedure declarations.
* update the language definition
* implement the feature in `source2il`, by passing the body expression
to `fitExpr` and wrapping non-void expression in a `Return` expression
---
* a small out-of-band improvement to the language
=> lang: allow non-void expressions as bodies

languages/source.nim, tests/expr/t13_usage_in_at.test, tests/expr/t17_seq_at_eval_order_3.test
Also allow evaluation/reduction of the index operand of an `At`
expression when the array operand is not an lvalue expression.
* add an `As` pattern to both `E` and `F` that admits all `val` in the
array operand position
* add two tests, one covering the `(As val le)` case and one the
`(As val e)` case
---
* I missed adding these rules with #127
* blocks #122
=> spec: add missing `At` context rules

spec/bignums.nim, spec/builtin.nim, spec/manual.md, tests/unittest/tbignums.nim
* add a native `Bignum` implementation (`bignums.nim`)
* use `Bignum` for all arithmetic/comparison operations in the
interpreter
A NimSkull-native `Bignum` implementation is used because:
* porting it to the source language in the future will be easier / can
be automated
* the repository stays self-contained
Two explicit goals the implementation were that it's fully usable at
compile-time (in the VM) and that zero-initialized `Bignum`s are valid.
The implementation tries to strike a balance between complexity and
efficiency, usually preferring a simpler over a more efficient
implementation.
Using two's complement representation gets around having an extra sign
flag, which would increase the size of `Bignum`s by 8 byte (on a 64-bit
target).
Tests based on the `int128` tests are added for …
=> use arbitrary-precision integers in the meta language 

spec/builtin.nim
Fix the `updated` implementation not compiling due to still assuming
that numeric values are represented as `Int128`.
=> builtin: fix a compilation error

.github/workflows/build_and_test.yml, skully/backend.nim, skully/passes.nim
* fix code generator bug with skully, leading to crashes of the
compiled code
* update to the `0.1.0-dev.21449` NimSkull compiler
The `if` expressions emitted for `and` and `or` in the MIR currently
open no scope, meaning that the lifetime of temporaries created within
extend into the `if`'s scope.
Skully's code generator emits the location only for `def` statements,
and thus locations for which the `def` is in an unscoped `if` are in an
undefined state when the `if` is not entered, potentially leading to
memory corruption or access violations when using the location's
content (e.g., during destruction).
A MIR pass is added that moves moves the problematic `def`s (but not
the assignment) to right before the unscoped `if`, making all usages of
a location are dominated by the location's …
=> skully: fix codegen for setup of temporaries

languages/source.nim, passes/source2il.nim, tests/expr/spectest.nim, tests/expr/t03_tuple_at_1.test, tests/expr/t03_tuple_at_10.test, tests/expr/t03_tuple_at_11.test, tests/expr/t03_tuple_at_2.test, tests/expr/t03_tuple_at_3.test, tests/expr/t03_tuple_at_4.test, tests/expr/t03_tuple_at_5.test, tests/expr/t03_tuple_at_6.test, tests/expr/t03_tuple_at_7.test, tests/expr/t03_tuple_at_8.test, tests/expr/t03_tuple_at_9.test, tests/expr/t03_tuple_at_eval_order_1.test, tests/expr/t03_tuple_at_eval_order_2.test, tests/expr/t03_tuple_at_eval_order_3.test, tests/expr/t03_tuple_at_eval_order_4.test, tests/expr/t03_tuple_at_eval_order_5.test, tests/expr/t10_asgn_lhs_must_be_lvalue_11_error.test, tests/expr/t10_asgn_lhs_must_be_lvalue_12_error.test
Extend `At` to also allow tuple values as the first operand. If the
tuple is homogeneous, the expression has the type of the tuple element,
otherwise it's a union of all possible element types.
* add a typing rule for `At` with tuples
* add reduction rules for `At` and `With` covering tuples
* implement `At` support for tuple values in `source2il`
* fix a bug with `source2il.align` that resulted in the wrong value
being returned (the mask was computed incorrectly)
`At` with a tuple operand never yields a mutable lvalue, even if the
input is one, as it'll make the future initial implementation of
pattern matching easier, but this decision is subject to change.
---
* depends on #122 to work
=> lang: add dynamic tuple indexing

.github/workflows/build_and_test.yml, spec/cps.nim, spec/interpreter.nim
Start with using tail calls for the continuations in the `interpret`
procedure. This prevents stack overflows when interpreting functions
with very complex bodies.
So far, continuations were just arbitrary closures, but now they're
`.tailcall` procedures. Anonymous `.tailcall` procedure cannot capture
outer variables, so captures have to be handled manually. A small set of
simple macro helpers (the `cps` module) is introduced to eliminate the
boilerplate code this would entail.
The main change is made out of two parts:
1. the lambda sugar is replaced with `proc(...): ...` that use the
`.cont` calling convention (which is a macro pragma)
2. where sensible and necessary, procedure parameters use `sink`, and
owning locals and parameter are destroyed manually, using the `drop`
helper. The …
=> interpreter: start with using tail calls

.github/workflows/build_and_test.yml, passes/ir.nim, passes/pass25.nim, passes/pass30.nim, passes/pass_aggregatesToBlob.nim, passes/pass_legalizeBlobOps.nim, passes/pass_localsToBlob.nim, passes/pass_stackAlloc.nim, passes/syntax.nim, passes/syntax_source.nim, phy/reporting.nim, phy/type_rendering.nim, phy/types.nim, skully/backend.nim, vm/utils.nim
* replace the custom `unreachable` with the NimSkull-built-in one
* bump the minimum-required NimSkull version to `0.1.0-dev.21464`
* remove the custom `unreachable` implementation
* remove all now-unused imports of `vm/utils`
* use the `std/private/containers` module instead of `compiler/utils/containers`
=> use the built-in `unreachable`

languages/source.nim, phy/queryshell.nim, spec/interpreter.nim, spec/langdefs.nim, spec/manual.md, spec/types.nim, tests/expr/spectest.nim
* assign a dedicated type to constructor patterns in a `typ` declaration
* distinguish between `A` and `A()` (value vs. nullary construction)
* slightly clean up type checking and speed it up
The type checker and type system are changed as follows:
* patterns representing types are now treated as such, using the
`tkPat` type kind
* distinguish between `A` and `A()`. Both are now disjoint terms
* the `tkData` type kind is removed. `typ` and `subtype` declaration
now create (potentially recursive) sums of pattern types
The changes allow for more narrow typing of value constructions.
Previously, they had to be typed as the *data type* matching the
construction, which is unnecessarily broad and necessitated `or` types
in order to be able to resolve ambiguity (i.e., when a construction
is …
=> improve the meta-language's type system

spec/interpreter.nim
Make the routines involved in list pattern matching `.tailcall`
routines. Usage of complex list patterns can no longer cause a stack
overflow (by itself).
So that tail-calling is possible, all list matching routines now fully
use continuation-passing style, instead of a mixture between it and
direct style.
As a consequence, repetition matching becomes more complex, as it can
no longer inspect the return value of the "rest". Instead, it needs
access to both the "rest" *and* the return continuation of the "rest",
so that it can logically intercept the return.
The way the implementation now works means that a repetition pattern
nested in a group no longer works, but this was never explicitly
supported anyway and it's also disallowed by the meta-language's
semantic checker.
---
* another step …
=> interpreter: use tail-calls for list matching

.github/workflows/build_and_test.yml, spec/cps.nim
Use the most recent NimSkull version and selectively disable runtime
type checks. Interpreter performance is now closer to what it was prior
to the usage of tail calls for pattern matching, and memory usage no
longer grows indefinitely.
* using the most recent NimSkull version fixes both a severe memory leak
and a lot unnecessary copies
* the object conversion type checks in `cps.take` made up ~25% of the
execution time of `spectest`. Since the checks are unnecessary (the
way `CellRef` is used makes dynamic type errors impossible), they're
disabled
=> partially restore interpreter performance

koch.nim, languages/core.nim, tests/expr/spectest.nim
In preparation for splitting the source language from the core language
definition, `source.nim` is renamed to `core.nim`, as it's mostly made
up of the core language definition.
---
Separate from the main split-up so that git history for most of the core language definition is kept intact.
=> rename `source.nim` to `core.nim`

phy/phy.nim, phy/tracing.nim
Add the `--measure` switch to `phy`, which allows dumping internal
timings gathered for various steps. This is intended as a development
and optimization aid.
* add the `tracing` module, which implements a simple time-stamped-
event log collection facility (`EventLog`)
* use `EventLog` to collect the start and end times for each internal
pass, as well as `source2il` and VM code generation
* the timings are gathered from the log, rendered as a CSV list, and
dumped to the standard output
To continue supporting compiling `phy` with `skully`, instrumentation is
disabled (at compile time), as the `times` and `monotimes` standard
library modules cannot be imported when using `--os:any` (which `skully`
always does).
---
* `tracing` is effectively a heavily trimmed-down, more generic version of …
=> phy: instrument pass execution

tests/pass0/t03_demote_float64_to_float32.expected, vm/disasm.nim
The output for VM constants was missing the type, meaning that it
wasn't a valid assembler directive.
=> disasm: fix output for constants

.github/workflows/build_and_test.yml, README.md, koch.nim
Replace the `single` and `all` commands with the more intuitive `build`
command. `build all` builds all programs (including `skully`), whereas
`build all-ws` builds all programs *except* `skully`.
The build logic in `skully` is restructured to be more generic. To make
lookup easier, the list of programs is now defined using a table, not
a sequence, with the program name used as the key.
For performance reasons, CI continues to build and test `skully`
separately from the other programs.
=> koch: replace `single` and `all` with `build`

phy/phy.nim, phy/repl.nim, phy/vmexec.nim, tests/vm/t08_relocation.test, tests/vm/t09_init.test, vm/assembler.nim, vm/disasm.nim, vm/vmalloc.nim, vm/vmmodules.nim, vm/vmvalidation.nim
Add native support for memory management to VM modules, for allocating,
initializing, and referencing global memory.
To support programs made up of multiple, not-available-up-front modules,
where the current global memory management via the configuration
variables doesn't work well, VM modules now support:
* specifying a required memory size (`.memory`), which is allocated from
the VM's global memory when the module is loaded
* memory initializers (`.init`), for initializing memory regions with
constant data when the module is loaded
* relocations (`.reloc`), which allow storing offsets into the module's
memory, and have be turned into a proper virtual address upon module
load
The core VM does *not* change.
For temporary backwards compatibility, the existing configuration
variables still …
=> vmmodules: add support for module memory

languages/lang0.md, languages/lang25.md, languages/lang6.md, passes/pass0.nim, passes/pass25.nim, passes/pass_globalsToPointer.nim, passes/syntax.nim, phy/phy.nim, phy/repl.nim, tests/pass0/t05_data_init.expected, tests/pass0/t05_data_init.test, tests/pass0/t05_data_layout.expected, tests/pass0/t05_data_layout.test, tests/pass0/t05_data_uninit.expected, tests/pass0/t05_data_uninit.test, tests/passes/globals_to_pointer/addr.expected, tests/passes/globals_to_pointer/addr.test, tests/passes/globals_to_pointer/asgn.expected, tests/passes/globals_to_pointer/asgn.test, tests/passes/globals_to_pointer/copy.expected, tests/passes/globals_to_pointer/copy.test, tests/passes/globals_to_pointer/globals.expected, tests/passes/globals_to_pointer/globals.test, tests/passes/globals_to_pointer/runner.txt
* add the `L6` IL, providing mutable global locations
* extend the `L0` IL with memory region support (`Data`)
* add the `Data` initializer for globals to the `L0` IL, which provides
a convenient interface for VM module memory regions, initializer, and
relocations
* implement the `Data` initializer in `pass0` and add tests for it
* add the `L6` IL, which extends the `L5` IL and is the new basis for
the `L25` IL. It introduces `GlobalLoc` definitions, which define
mutable global locations
* implement an `L6` -> `L5` lowering pass (`pass_globalsToPointer`) and
add tests for it
Past the `L6`, a distinction between global locations (`GlobalLoc`) and
global constants (`GlobalDef`) still has to be kept for now, as the
legacy memory configuration still relies on global constants.
=> add an IL with global locations

skully/backend.nim
Fix various bugs with `skully`. For the most part, they were about
incorrect code being emitted, resulting in misbehaving programs.
* fix size/alignment of embedded records (has no observable effect on
compilation, at the moment)
* fix `nil` not being handled in constants, causing a crash
* fix incorrect code being emitted for closure equality tests
* fix pointer-location default initialization using an integer zero
* fix zero being used instead of `Nil` in various places
* fix wrong conversion operators being used for integer conversion
* fix integer extension conversion operators not being emitted
* fix `ord` not being translated to a conversion
* fix code emitted for `mDestroy` accessing the wrong field
* fix wrong code being emitted for `cast` where at least one operand is
a float or …
=> skully: fix various bugs

languages/specification.md, passes/source2il.nim, tests/expr/t05_char_type.nim
Allow `CharTy` being used as a type expression, as specified by the
language definition.
`CharTy` appearing anywhere was erroneously considered a syntax error,
previously.
=> source2il: implement `CharTy` support

passes/source2il.nim, phy/types.nim, tests/expr/t17_seq_copy_6.test
Fix the compiler crashing for code where a record having a seq member
is copied.
The implementation for non-trivially-copyable records was missing,
causing the `unreachable` to trigger.
In order to prevent similar bugs going forward, the case statement for
producing the copy implementation is made exhaustive, using the new
`AllTypes` set. If a new aggregate type is added in the future, a
compile-time error will be reported if the new type is not handled.
=> source2il: fix crash when copying records

passes/source2il.nim, phy/type_rendering.nim, tests/errors/README.md, tests/errors/terror_in_call_argument.test, tests/errors/terror_in_if.test, tests/errors/terror_in_if_1.test, tests/errors/terror_in_if_2.test, tests/errors/terror_in_tuple_cons.test
Fix the compiler crashing for some instances of semantically
invalid code.
Error types reached into `typeToString`, triggering the `unreachable`
assertion and thus crashing the compiler.
* change `typeToString` to render errors as `?`. There are valid cases
for an error type being rendered, such as when it's part of a
composite type
* improve error recovery for tuple analysis. An element being an error
no longer short-circuits analysis by returning an error
* use a single procedure for handling type unification (`unify`). This
fixes unnecessary follow-up errors being reported for an `If` where
unification fails due to one type being an error
* don't report unnecessary follow-up errors in `fitExprStrict`
Tests are added to make sure code that previously crashed the compiler
no longer does. …
=> source2il: fix crashes with erroneous code
